version: "3.9"

x-common-django-settings: &common_django_settings
    networks:
        - backend_net
    restart: always
    deploy:
        mode: replicated
        replicas: 1
        update_config:
            parallelism: 1
            delay: 5s
            order: start-first
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 5
            window: 30s
        resources:
            limits:
                cpus: "1.0"
                memory: 768M
            reservations:
                cpus: "0.5"
                memory: 384M
    env_file:
        - ./.env

services:
    postgres:
        image: postgres:16-alpine
        secrets:
            - kasana_postgres_password
            - kasana_postgres_username
        environment:
            POSTGRES_USER_FILE: /run/secrets/kasana_postgres_username
            POSTGRES_PASSWORD_FILE: /run/secrets/kasana_postgres_password
            POSTGRES_DB: "kasana_database"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - backend_net
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "2.0"
                    memory: 2G
                reservations:
                    cpus: "1.0"
                    memory: 1G

    pgbouncer:
        image: edoburu/pgbouncer
        configs:
            - source: pgbouncer_ini
              target: /etc/pgbouncer/pgbouncer.ini
            - source: pgbouncer_userlist
              target: /etc/pgbouncer/userlist.txt
            - source: pgbouncer_entrypoint
              target: /usr/local/bin/pgbouncer-entrypoint.sh
        entrypoint: ["/bin/sh", "/usr/local/bin/pgbouncer-entrypoint.sh"]
        healthcheck:
            test: ["CMD", "pg_isready", "-h", "localhost", "-p", "6432"]
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - backend_net
        ports:
            - target: 6432
              published: 9980
              protocol: tcp
              mode: host
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.25"
                    memory: 128M
                reservations:
                    cpus: "0.1"
                    memory: 64M

    redis:
        image: redis:7.2
        volumes:
            - redis_data:/data
        networks:
            - backend_net
        depends_on:
            - pgbouncer
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 3
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1.0"
                    memory: 1G
                reservations:
                    cpus: "0.5"
                    memory: 512M

    users-service:
        <<: *common_django_settings
        image: ghcr.io/abdulkhafizov07/kasana/users-backend:main
        environment:
            DJANGO_INSTALLED_APPS: "apps.users_main,apps.api,apps.users,apps.dashboard.apps.DashboardConfig"

    onlineshop-service:
        <<: *common_django_settings
        image: ghcr.io/abdulkhafizov07/kasana/onlineshop-backend:main
        environment:
            DJANGO_INSTALLED_APPS: "apps.onlineshop_main,apps.api,apps.users,apps.dashboard.apps.DashboardConfig"

    town-service:
        <<: *common_django_settings
        image: ghcr.io/abdulkhafizov07/kasana/town-backend:main
        environment:
            DJANGO_INSTALLED_APPS: "apps.messages_main,apps.api,apps.users"

    announcements-service:
        <<: *common_django_settings
        image: ghcr.io/abdulkhafizov07/kasana/announcements-backend:main
        environment:
            DJANGO_INSTALLED_APPS: "apps.announcements_main,apps.api,apps.users,apps.dashboard.apps.DashboardConfig"

    news-service:
        <<: *common_django_settings
        image: ghcr.io/abdulkhafizov07/kasana/news-backend:main
        environment:
            DJANGO_INSTALLED_APPS: "apps.news_main,apps.api,apps.users,apps.dashboard.apps.DashboardConfig"

    courses-service:
        <<: *common_django_settings
        image: ghcr.io/abdulkhafizov07/kasana/courses-backend:main
        environment:
            DJANGO_INSTALLED_APPS: "apps.courses_main,apps.api,apps.users,apps.dashboard.apps.DashboardConfig"

    frontend-service:
        image: ghcr.io/abdulkhafizov07/kasana/frontend:main
        ports:
            - target: 3000
              published: 13444
              protocol: tcp
              mode: ingress
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: "0.5"
                    memory: 256M
                reservations:
                    cpus: "0.25"
                    memory: 128M

    nginx:
        image: nginx:alpine
        ports:
            - target: 80
              published: 13445
              protocol: tcp
              mode: host
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - backend_net
        depends_on:
            - users-service
            - onlineshop-service
            - announcements-service
            - news-service
            - courses-service
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "0.5"
                    memory: 256M
                reservations:
                    cpus: "0.25"
                    memory: 128M

    minio:
        image: minio/minio
        environment:
            MINIO_ROOT_USER: files_admin
            MINIO_ROOT_PASSWORD: why?so4why?
        command: server --address ":9000" --console-address ":44061" /data
        volumes:
            - minio_data:/data
        networks:
            - backend_net
        ports:
            - target: 9000
              published: 9000
              protocol: tcp
              mode: host
            - target: 44061
              published: 44061
              protocol: tcp
              mode: host
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/ready || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1.0"
                    memory: 1G
                reservations:
                    cpus: "0.5"
                    memory: 512M

    prometheus:
        image: prom/prometheus:latest
        configs:
            - source: prometheus_yml
              target: /etc/prometheus/prometheus.yml
        ports:
            - target: 9090
              published: 9090
              protocol: tcp
              mode: host
        networks:
            - backend_net
        healthcheck:
            test: ["CMD-SHELL", "wget -qO- http://localhost:9090/-/healthy || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 3
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1.0"
                    memory: 1G
                reservations:
                    cpus: "0.5"
                    memory: 512M

    grafana:
        image: grafana/grafana:latest
        ports:
            - target: 3000
              published: 3000
              protocol: tcp
              mode: host
        environment:
            GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
            GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
        volumes:
            - grafana_data:/var/lib/grafana
        networks:
            - backend_net
        healthcheck:
            test: ["CMD-SHELL", "wget -qO- http://localhost:3000/api/health || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M
                reservations:
                    cpus: "0.25"
                    memory: 256M

networks:
    backend_net:
        driver: overlay

volumes:
    redis_data:
    grafana_data:
    clickhouse_data:
    postgres_data:
    minio_data:

configs:
    pgbouncer_ini:
        file: ./pgbouncer/conf/pgbouncer.ini
    pgbouncer_userlist:
        file: ./pgbouncer/conf/userlist.txt
    pgbouncer_entrypoint:
        file: ./pgbouncer/entrypoint.sh
    prometheus_yml:
        file: ./monitoring/prometheus.yml

secrets:
    kasana_postgres_username:
        external: true
    kasana_postgres_password:
        external: true
