/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements/index'
import { Route as ShopCategoriesRouteImport } from './routes/shop/categories'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthOneidRouteImport } from './routes/auth/oneid'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AnnouncementsWorkRouteImport } from './routes/announcements/work'
import { Route as AnnouncementsServiceRouteImport } from './routes/announcements/service'
import { Route as AnnouncementsCreateRouteImport } from './routes/announcements/create'
import { Route as ShopDetailsProductRouteImport } from './routes/shop/details.$product'
import { Route as NewsNewsMetaRouteImport } from './routes/news/news.$meta'
import { Route as NewsCategoriesMetaRouteImport } from './routes/news/categories.$meta'
import { Route as CoursesDetailsMetaRouteImport } from './routes/courses/details.$meta'
import { Route as CoursesCategoryMetaRouteImport } from './routes/courses/category.$meta'
import { Route as AnnouncementsWorkMetaRouteImport } from './routes/announcements/work.$meta'
import { Route as AnnouncementsServiceMetaRouteImport } from './routes/announcements/service.$meta'
import { Route as AuthenticatedProfileProfileLayoutRouteImport } from './routes/_authenticated/profile/_profileLayout'
import { Route as AuthenticatedAdminAdminLayoutRouteImport } from './routes/_authenticated/admin/_adminLayout'
import { Route as AuthenticatedProfileProfileLayoutIndexRouteImport } from './routes/_authenticated/profile/_profileLayout/index'
import { Route as AuthenticatedAdminAdminLayoutIndexRouteImport } from './routes/_authenticated/admin/_adminLayout/index'
import { Route as AuthenticatedProfileProfileLayoutSavedAnnouncementsRouteImport } from './routes/_authenticated/profile/_profileLayout/saved-announcements'
import { Route as AuthenticatedProfileProfileLayoutOverviewRouteImport } from './routes/_authenticated/profile/_profileLayout/overview'
import { Route as AuthenticatedProfileProfileLayoutNotificationsRouteImport } from './routes/_authenticated/profile/_profileLayout/notifications'
import { Route as AuthenticatedProfileProfileLayoutMessengerRouteImport } from './routes/_authenticated/profile/_profileLayout/messenger'
import { Route as AuthenticatedProfileProfileLayoutLikedProductsRouteImport } from './routes/_authenticated/profile/_profileLayout/liked-products'
import { Route as AuthenticatedProfileProfileLayoutLikedCoursesRouteImport } from './routes/_authenticated/profile/_profileLayout/liked-courses'
import { Route as AuthenticatedProfileProfileLayoutEditRouteImport } from './routes/_authenticated/profile/_profileLayout/edit'
import { Route as AuthenticatedProfileProfileLayoutCoursesRouteImport } from './routes/_authenticated/profile/_profileLayout/courses'
import { Route as AuthenticatedProfileProfileLayoutAnnouncementsRouteImport } from './routes/_authenticated/profile/_profileLayout/announcements'
import { Route as AuthenticatedAdminAdminLayoutOverviewRouteImport } from './routes/_authenticated/admin/_adminLayout/overview'
import { Route as AuthenticatedAdminAdminLayoutLogsRouteImport } from './routes/_authenticated/admin/_adminLayout/logs'
import { Route as AuthenticatedProfileProfileLayoutProductsIndexRouteImport } from './routes/_authenticated/profile/_profileLayout/products/index'
import { Route as AuthenticatedAdminAdminLayoutUsersIndexRouteImport } from './routes/_authenticated/admin/_adminLayout/users/index'
import { Route as AuthenticatedAdminAdminLayoutOnlineshopIndexRouteImport } from './routes/_authenticated/admin/_adminLayout/onlineshop/index'
import { Route as AuthenticatedAdminAdminLayoutNewsIndexRouteImport } from './routes/_authenticated/admin/_adminLayout/news/index'
import { Route as AuthenticatedAdminAdminLayoutCoursesIndexRouteImport } from './routes/_authenticated/admin/_adminLayout/courses/index'
import { Route as AuthenticatedAdminAdminLayoutAnnouncementsIndexRouteImport } from './routes/_authenticated/admin/_adminLayout/announcements/index'
import { Route as AuthenticatedProfileProfileLayoutProductsCreateRouteImport } from './routes/_authenticated/profile/_profileLayout/products/create'
import { Route as AuthenticatedAdminAdminLayoutUsersCreateRouteImport } from './routes/_authenticated/admin/_adminLayout/users/create'
import { Route as AuthenticatedAdminAdminLayoutUsersRoleRouteImport } from './routes/_authenticated/admin/_adminLayout/users/$role'
import { Route as AuthenticatedAdminAdminLayoutOnlineshopCategoriesRouteImport } from './routes/_authenticated/admin/_adminLayout/onlineshop/categories'
import { Route as AuthenticatedAdminAdminLayoutNewsCategoriesRouteImport } from './routes/_authenticated/admin/_adminLayout/news/categories'
import { Route as AuthenticatedAdminAdminLayoutCoursesCategoriesRouteImport } from './routes/_authenticated/admin/_adminLayout/courses/categories'
import { Route as AuthenticatedAdminAdminLayoutAnnouncementsCreateRouteImport } from './routes/_authenticated/admin/_adminLayout/announcements/create'
import { Route as AuthenticatedAdminAdminLayoutAnnouncementsTypeRouteImport } from './routes/_authenticated/admin/_adminLayout/announcements/$type'
import { Route as AuthenticatedAdminAdminLayoutOnlineshopProductsIndexRouteImport } from './routes/_authenticated/admin/_adminLayout/onlineshop/products/index'
import { Route as AuthenticatedAdminAdminLayoutNewsNewsIndexRouteImport } from './routes/_authenticated/admin/_adminLayout/news/news/index'
import { Route as AuthenticatedAdminAdminLayoutNewsDocumentsIndexRouteImport } from './routes/_authenticated/admin/_adminLayout/news/documents/index'
import { Route as AuthenticatedAdminAdminLayoutCoursesCoursesIndexRouteImport } from './routes/_authenticated/admin/_adminLayout/courses/courses/index'
import { Route as AuthenticatedAdminAdminLayoutOnlineshopProductsCreateRouteImport } from './routes/_authenticated/admin/_adminLayout/onlineshop/products/create'
import { Route as AuthenticatedAdminAdminLayoutNewsNewsCreateRouteImport } from './routes/_authenticated/admin/_adminLayout/news/news/create'
import { Route as AuthenticatedAdminAdminLayoutNewsDocumentsCreateRouteImport } from './routes/_authenticated/admin/_adminLayout/news/documents/create'
import { Route as AuthenticatedAdminAdminLayoutCoursesCoursesCreateRouteImport } from './routes/_authenticated/admin/_adminLayout/courses/courses/create'

const AuthenticatedProfileRouteImport = createFileRoute(
  '/_authenticated/profile',
)()
const AuthenticatedAdminRouteImport = createFileRoute('/_authenticated/admin')()

const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoriesRoute = ShopCategoriesRouteImport.update({
  id: '/shop/categories',
  path: '/shop/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOneidRoute = AuthOneidRouteImport.update({
  id: '/auth/oneid',
  path: '/auth/oneid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsWorkRoute = AnnouncementsWorkRouteImport.update({
  id: '/announcements/work',
  path: '/announcements/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsServiceRoute = AnnouncementsServiceRouteImport.update({
  id: '/announcements/service',
  path: '/announcements/service',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsCreateRoute = AnnouncementsCreateRouteImport.update({
  id: '/announcements/create',
  path: '/announcements/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopDetailsProductRoute = ShopDetailsProductRouteImport.update({
  id: '/shop/details/$product',
  path: '/shop/details/$product',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsMetaRoute = NewsNewsMetaRouteImport.update({
  id: '/news/news/$meta',
  path: '/news/news/$meta',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsCategoriesMetaRoute = NewsCategoriesMetaRouteImport.update({
  id: '/news/categories/$meta',
  path: '/news/categories/$meta',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesDetailsMetaRoute = CoursesDetailsMetaRouteImport.update({
  id: '/courses/details/$meta',
  path: '/courses/details/$meta',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCategoryMetaRoute = CoursesCategoryMetaRouteImport.update({
  id: '/courses/category/$meta',
  path: '/courses/category/$meta',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsWorkMetaRoute = AnnouncementsWorkMetaRouteImport.update({
  id: '/$meta',
  path: '/$meta',
  getParentRoute: () => AnnouncementsWorkRoute,
} as any)
const AnnouncementsServiceMetaRoute =
  AnnouncementsServiceMetaRouteImport.update({
    id: '/$meta',
    path: '/$meta',
    getParentRoute: () => AnnouncementsServiceRoute,
  } as any)
const AuthenticatedProfileProfileLayoutRoute =
  AuthenticatedProfileProfileLayoutRouteImport.update({
    id: '/_profileLayout',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedAdminAdminLayoutRoute =
  AuthenticatedAdminAdminLayoutRouteImport.update({
    id: '/_adminLayout',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedProfileProfileLayoutIndexRoute =
  AuthenticatedProfileProfileLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileProfileLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutIndexRoute =
  AuthenticatedAdminAdminLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedProfileProfileLayoutSavedAnnouncementsRoute =
  AuthenticatedProfileProfileLayoutSavedAnnouncementsRouteImport.update({
    id: '/saved-announcements',
    path: '/saved-announcements',
    getParentRoute: () => AuthenticatedProfileProfileLayoutRoute,
  } as any)
const AuthenticatedProfileProfileLayoutOverviewRoute =
  AuthenticatedProfileProfileLayoutOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedProfileProfileLayoutRoute,
  } as any)
const AuthenticatedProfileProfileLayoutNotificationsRoute =
  AuthenticatedProfileProfileLayoutNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedProfileProfileLayoutRoute,
  } as any)
const AuthenticatedProfileProfileLayoutMessengerRoute =
  AuthenticatedProfileProfileLayoutMessengerRouteImport.update({
    id: '/messenger',
    path: '/messenger',
    getParentRoute: () => AuthenticatedProfileProfileLayoutRoute,
  } as any)
const AuthenticatedProfileProfileLayoutLikedProductsRoute =
  AuthenticatedProfileProfileLayoutLikedProductsRouteImport.update({
    id: '/liked-products',
    path: '/liked-products',
    getParentRoute: () => AuthenticatedProfileProfileLayoutRoute,
  } as any)
const AuthenticatedProfileProfileLayoutLikedCoursesRoute =
  AuthenticatedProfileProfileLayoutLikedCoursesRouteImport.update({
    id: '/liked-courses',
    path: '/liked-courses',
    getParentRoute: () => AuthenticatedProfileProfileLayoutRoute,
  } as any)
const AuthenticatedProfileProfileLayoutEditRoute =
  AuthenticatedProfileProfileLayoutEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedProfileProfileLayoutRoute,
  } as any)
const AuthenticatedProfileProfileLayoutCoursesRoute =
  AuthenticatedProfileProfileLayoutCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedProfileProfileLayoutRoute,
  } as any)
const AuthenticatedProfileProfileLayoutAnnouncementsRoute =
  AuthenticatedProfileProfileLayoutAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedProfileProfileLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutOverviewRoute =
  AuthenticatedAdminAdminLayoutOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutLogsRoute =
  AuthenticatedAdminAdminLayoutLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedProfileProfileLayoutProductsIndexRoute =
  AuthenticatedProfileProfileLayoutProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedProfileProfileLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutUsersIndexRoute =
  AuthenticatedAdminAdminLayoutUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutOnlineshopIndexRoute =
  AuthenticatedAdminAdminLayoutOnlineshopIndexRouteImport.update({
    id: '/onlineshop/',
    path: '/onlineshop/',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutNewsIndexRoute =
  AuthenticatedAdminAdminLayoutNewsIndexRouteImport.update({
    id: '/news/',
    path: '/news/',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutCoursesIndexRoute =
  AuthenticatedAdminAdminLayoutCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutAnnouncementsIndexRoute =
  AuthenticatedAdminAdminLayoutAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedProfileProfileLayoutProductsCreateRoute =
  AuthenticatedProfileProfileLayoutProductsCreateRouteImport.update({
    id: '/products/create',
    path: '/products/create',
    getParentRoute: () => AuthenticatedProfileProfileLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutUsersCreateRoute =
  AuthenticatedAdminAdminLayoutUsersCreateRouteImport.update({
    id: '/users/create',
    path: '/users/create',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutUsersRoleRoute =
  AuthenticatedAdminAdminLayoutUsersRoleRouteImport.update({
    id: '/users/$role',
    path: '/users/$role',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutOnlineshopCategoriesRoute =
  AuthenticatedAdminAdminLayoutOnlineshopCategoriesRouteImport.update({
    id: '/onlineshop/categories',
    path: '/onlineshop/categories',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutNewsCategoriesRoute =
  AuthenticatedAdminAdminLayoutNewsCategoriesRouteImport.update({
    id: '/news/categories',
    path: '/news/categories',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutCoursesCategoriesRoute =
  AuthenticatedAdminAdminLayoutCoursesCategoriesRouteImport.update({
    id: '/courses/categories',
    path: '/courses/categories',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutAnnouncementsCreateRoute =
  AuthenticatedAdminAdminLayoutAnnouncementsCreateRouteImport.update({
    id: '/announcements/create',
    path: '/announcements/create',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutAnnouncementsTypeRoute =
  AuthenticatedAdminAdminLayoutAnnouncementsTypeRouteImport.update({
    id: '/announcements/$type',
    path: '/announcements/$type',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutOnlineshopProductsIndexRoute =
  AuthenticatedAdminAdminLayoutOnlineshopProductsIndexRouteImport.update({
    id: '/onlineshop/products/',
    path: '/onlineshop/products/',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutNewsNewsIndexRoute =
  AuthenticatedAdminAdminLayoutNewsNewsIndexRouteImport.update({
    id: '/news/news/',
    path: '/news/news/',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutNewsDocumentsIndexRoute =
  AuthenticatedAdminAdminLayoutNewsDocumentsIndexRouteImport.update({
    id: '/news/documents/',
    path: '/news/documents/',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutCoursesCoursesIndexRoute =
  AuthenticatedAdminAdminLayoutCoursesCoursesIndexRouteImport.update({
    id: '/courses/courses/',
    path: '/courses/courses/',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutOnlineshopProductsCreateRoute =
  AuthenticatedAdminAdminLayoutOnlineshopProductsCreateRouteImport.update({
    id: '/onlineshop/products/create',
    path: '/onlineshop/products/create',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutNewsNewsCreateRoute =
  AuthenticatedAdminAdminLayoutNewsNewsCreateRouteImport.update({
    id: '/news/news/create',
    path: '/news/news/create',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutNewsDocumentsCreateRoute =
  AuthenticatedAdminAdminLayoutNewsDocumentsCreateRouteImport.update({
    id: '/news/documents/create',
    path: '/news/documents/create',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)
const AuthenticatedAdminAdminLayoutCoursesCoursesCreateRoute =
  AuthenticatedAdminAdminLayoutCoursesCoursesCreateRouteImport.update({
    id: '/courses/courses/create',
    path: '/courses/courses/create',
    getParentRoute: () => AuthenticatedAdminAdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/announcements/create': typeof AnnouncementsCreateRoute
  '/announcements/service': typeof AnnouncementsServiceRouteWithChildren
  '/announcements/work': typeof AnnouncementsWorkRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/oneid': typeof AuthOneidRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/shop/categories': typeof ShopCategoriesRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/news': typeof NewsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/admin': typeof AuthenticatedAdminAdminLayoutRouteWithChildren
  '/profile': typeof AuthenticatedProfileProfileLayoutRouteWithChildren
  '/announcements/service/$meta': typeof AnnouncementsServiceMetaRoute
  '/announcements/work/$meta': typeof AnnouncementsWorkMetaRoute
  '/courses/category/$meta': typeof CoursesCategoryMetaRoute
  '/courses/details/$meta': typeof CoursesDetailsMetaRoute
  '/news/categories/$meta': typeof NewsCategoriesMetaRoute
  '/news/news/$meta': typeof NewsNewsMetaRoute
  '/shop/details/$product': typeof ShopDetailsProductRoute
  '/admin/logs': typeof AuthenticatedAdminAdminLayoutLogsRoute
  '/admin/overview': typeof AuthenticatedAdminAdminLayoutOverviewRoute
  '/profile/announcements': typeof AuthenticatedProfileProfileLayoutAnnouncementsRoute
  '/profile/courses': typeof AuthenticatedProfileProfileLayoutCoursesRoute
  '/profile/edit': typeof AuthenticatedProfileProfileLayoutEditRoute
  '/profile/liked-courses': typeof AuthenticatedProfileProfileLayoutLikedCoursesRoute
  '/profile/liked-products': typeof AuthenticatedProfileProfileLayoutLikedProductsRoute
  '/profile/messenger': typeof AuthenticatedProfileProfileLayoutMessengerRoute
  '/profile/notifications': typeof AuthenticatedProfileProfileLayoutNotificationsRoute
  '/profile/overview': typeof AuthenticatedProfileProfileLayoutOverviewRoute
  '/profile/saved-announcements': typeof AuthenticatedProfileProfileLayoutSavedAnnouncementsRoute
  '/admin/': typeof AuthenticatedAdminAdminLayoutIndexRoute
  '/profile/': typeof AuthenticatedProfileProfileLayoutIndexRoute
  '/admin/announcements/$type': typeof AuthenticatedAdminAdminLayoutAnnouncementsTypeRoute
  '/admin/announcements/create': typeof AuthenticatedAdminAdminLayoutAnnouncementsCreateRoute
  '/admin/courses/categories': typeof AuthenticatedAdminAdminLayoutCoursesCategoriesRoute
  '/admin/news/categories': typeof AuthenticatedAdminAdminLayoutNewsCategoriesRoute
  '/admin/onlineshop/categories': typeof AuthenticatedAdminAdminLayoutOnlineshopCategoriesRoute
  '/admin/users/$role': typeof AuthenticatedAdminAdminLayoutUsersRoleRoute
  '/admin/users/create': typeof AuthenticatedAdminAdminLayoutUsersCreateRoute
  '/profile/products/create': typeof AuthenticatedProfileProfileLayoutProductsCreateRoute
  '/admin/announcements': typeof AuthenticatedAdminAdminLayoutAnnouncementsIndexRoute
  '/admin/courses': typeof AuthenticatedAdminAdminLayoutCoursesIndexRoute
  '/admin/news': typeof AuthenticatedAdminAdminLayoutNewsIndexRoute
  '/admin/onlineshop': typeof AuthenticatedAdminAdminLayoutOnlineshopIndexRoute
  '/admin/users': typeof AuthenticatedAdminAdminLayoutUsersIndexRoute
  '/profile/products': typeof AuthenticatedProfileProfileLayoutProductsIndexRoute
  '/admin/courses/courses/create': typeof AuthenticatedAdminAdminLayoutCoursesCoursesCreateRoute
  '/admin/news/documents/create': typeof AuthenticatedAdminAdminLayoutNewsDocumentsCreateRoute
  '/admin/news/news/create': typeof AuthenticatedAdminAdminLayoutNewsNewsCreateRoute
  '/admin/onlineshop/products/create': typeof AuthenticatedAdminAdminLayoutOnlineshopProductsCreateRoute
  '/admin/courses/courses': typeof AuthenticatedAdminAdminLayoutCoursesCoursesIndexRoute
  '/admin/news/documents': typeof AuthenticatedAdminAdminLayoutNewsDocumentsIndexRoute
  '/admin/news/news': typeof AuthenticatedAdminAdminLayoutNewsNewsIndexRoute
  '/admin/onlineshop/products': typeof AuthenticatedAdminAdminLayoutOnlineshopProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/announcements/create': typeof AnnouncementsCreateRoute
  '/announcements/service': typeof AnnouncementsServiceRouteWithChildren
  '/announcements/work': typeof AnnouncementsWorkRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/oneid': typeof AuthOneidRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/shop/categories': typeof ShopCategoriesRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/news': typeof NewsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/admin': typeof AuthenticatedAdminAdminLayoutIndexRoute
  '/profile': typeof AuthenticatedProfileProfileLayoutIndexRoute
  '/announcements/service/$meta': typeof AnnouncementsServiceMetaRoute
  '/announcements/work/$meta': typeof AnnouncementsWorkMetaRoute
  '/courses/category/$meta': typeof CoursesCategoryMetaRoute
  '/courses/details/$meta': typeof CoursesDetailsMetaRoute
  '/news/categories/$meta': typeof NewsCategoriesMetaRoute
  '/news/news/$meta': typeof NewsNewsMetaRoute
  '/shop/details/$product': typeof ShopDetailsProductRoute
  '/admin/logs': typeof AuthenticatedAdminAdminLayoutLogsRoute
  '/admin/overview': typeof AuthenticatedAdminAdminLayoutOverviewRoute
  '/profile/announcements': typeof AuthenticatedProfileProfileLayoutAnnouncementsRoute
  '/profile/courses': typeof AuthenticatedProfileProfileLayoutCoursesRoute
  '/profile/edit': typeof AuthenticatedProfileProfileLayoutEditRoute
  '/profile/liked-courses': typeof AuthenticatedProfileProfileLayoutLikedCoursesRoute
  '/profile/liked-products': typeof AuthenticatedProfileProfileLayoutLikedProductsRoute
  '/profile/messenger': typeof AuthenticatedProfileProfileLayoutMessengerRoute
  '/profile/notifications': typeof AuthenticatedProfileProfileLayoutNotificationsRoute
  '/profile/overview': typeof AuthenticatedProfileProfileLayoutOverviewRoute
  '/profile/saved-announcements': typeof AuthenticatedProfileProfileLayoutSavedAnnouncementsRoute
  '/admin/announcements/$type': typeof AuthenticatedAdminAdminLayoutAnnouncementsTypeRoute
  '/admin/announcements/create': typeof AuthenticatedAdminAdminLayoutAnnouncementsCreateRoute
  '/admin/courses/categories': typeof AuthenticatedAdminAdminLayoutCoursesCategoriesRoute
  '/admin/news/categories': typeof AuthenticatedAdminAdminLayoutNewsCategoriesRoute
  '/admin/onlineshop/categories': typeof AuthenticatedAdminAdminLayoutOnlineshopCategoriesRoute
  '/admin/users/$role': typeof AuthenticatedAdminAdminLayoutUsersRoleRoute
  '/admin/users/create': typeof AuthenticatedAdminAdminLayoutUsersCreateRoute
  '/profile/products/create': typeof AuthenticatedProfileProfileLayoutProductsCreateRoute
  '/admin/announcements': typeof AuthenticatedAdminAdminLayoutAnnouncementsIndexRoute
  '/admin/courses': typeof AuthenticatedAdminAdminLayoutCoursesIndexRoute
  '/admin/news': typeof AuthenticatedAdminAdminLayoutNewsIndexRoute
  '/admin/onlineshop': typeof AuthenticatedAdminAdminLayoutOnlineshopIndexRoute
  '/admin/users': typeof AuthenticatedAdminAdminLayoutUsersIndexRoute
  '/profile/products': typeof AuthenticatedProfileProfileLayoutProductsIndexRoute
  '/admin/courses/courses/create': typeof AuthenticatedAdminAdminLayoutCoursesCoursesCreateRoute
  '/admin/news/documents/create': typeof AuthenticatedAdminAdminLayoutNewsDocumentsCreateRoute
  '/admin/news/news/create': typeof AuthenticatedAdminAdminLayoutNewsNewsCreateRoute
  '/admin/onlineshop/products/create': typeof AuthenticatedAdminAdminLayoutOnlineshopProductsCreateRoute
  '/admin/courses/courses': typeof AuthenticatedAdminAdminLayoutCoursesCoursesIndexRoute
  '/admin/news/documents': typeof AuthenticatedAdminAdminLayoutNewsDocumentsIndexRoute
  '/admin/news/news': typeof AuthenticatedAdminAdminLayoutNewsNewsIndexRoute
  '/admin/onlineshop/products': typeof AuthenticatedAdminAdminLayoutOnlineshopProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/announcements/create': typeof AnnouncementsCreateRoute
  '/announcements/service': typeof AnnouncementsServiceRouteWithChildren
  '/announcements/work': typeof AnnouncementsWorkRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/oneid': typeof AuthOneidRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/shop/categories': typeof ShopCategoriesRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/_adminLayout': typeof AuthenticatedAdminAdminLayoutRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/profile/_profileLayout': typeof AuthenticatedProfileProfileLayoutRouteWithChildren
  '/announcements/service/$meta': typeof AnnouncementsServiceMetaRoute
  '/announcements/work/$meta': typeof AnnouncementsWorkMetaRoute
  '/courses/category/$meta': typeof CoursesCategoryMetaRoute
  '/courses/details/$meta': typeof CoursesDetailsMetaRoute
  '/news/categories/$meta': typeof NewsCategoriesMetaRoute
  '/news/news/$meta': typeof NewsNewsMetaRoute
  '/shop/details/$product': typeof ShopDetailsProductRoute
  '/_authenticated/admin/_adminLayout/logs': typeof AuthenticatedAdminAdminLayoutLogsRoute
  '/_authenticated/admin/_adminLayout/overview': typeof AuthenticatedAdminAdminLayoutOverviewRoute
  '/_authenticated/profile/_profileLayout/announcements': typeof AuthenticatedProfileProfileLayoutAnnouncementsRoute
  '/_authenticated/profile/_profileLayout/courses': typeof AuthenticatedProfileProfileLayoutCoursesRoute
  '/_authenticated/profile/_profileLayout/edit': typeof AuthenticatedProfileProfileLayoutEditRoute
  '/_authenticated/profile/_profileLayout/liked-courses': typeof AuthenticatedProfileProfileLayoutLikedCoursesRoute
  '/_authenticated/profile/_profileLayout/liked-products': typeof AuthenticatedProfileProfileLayoutLikedProductsRoute
  '/_authenticated/profile/_profileLayout/messenger': typeof AuthenticatedProfileProfileLayoutMessengerRoute
  '/_authenticated/profile/_profileLayout/notifications': typeof AuthenticatedProfileProfileLayoutNotificationsRoute
  '/_authenticated/profile/_profileLayout/overview': typeof AuthenticatedProfileProfileLayoutOverviewRoute
  '/_authenticated/profile/_profileLayout/saved-announcements': typeof AuthenticatedProfileProfileLayoutSavedAnnouncementsRoute
  '/_authenticated/admin/_adminLayout/': typeof AuthenticatedAdminAdminLayoutIndexRoute
  '/_authenticated/profile/_profileLayout/': typeof AuthenticatedProfileProfileLayoutIndexRoute
  '/_authenticated/admin/_adminLayout/announcements/$type': typeof AuthenticatedAdminAdminLayoutAnnouncementsTypeRoute
  '/_authenticated/admin/_adminLayout/announcements/create': typeof AuthenticatedAdminAdminLayoutAnnouncementsCreateRoute
  '/_authenticated/admin/_adminLayout/courses/categories': typeof AuthenticatedAdminAdminLayoutCoursesCategoriesRoute
  '/_authenticated/admin/_adminLayout/news/categories': typeof AuthenticatedAdminAdminLayoutNewsCategoriesRoute
  '/_authenticated/admin/_adminLayout/onlineshop/categories': typeof AuthenticatedAdminAdminLayoutOnlineshopCategoriesRoute
  '/_authenticated/admin/_adminLayout/users/$role': typeof AuthenticatedAdminAdminLayoutUsersRoleRoute
  '/_authenticated/admin/_adminLayout/users/create': typeof AuthenticatedAdminAdminLayoutUsersCreateRoute
  '/_authenticated/profile/_profileLayout/products/create': typeof AuthenticatedProfileProfileLayoutProductsCreateRoute
  '/_authenticated/admin/_adminLayout/announcements/': typeof AuthenticatedAdminAdminLayoutAnnouncementsIndexRoute
  '/_authenticated/admin/_adminLayout/courses/': typeof AuthenticatedAdminAdminLayoutCoursesIndexRoute
  '/_authenticated/admin/_adminLayout/news/': typeof AuthenticatedAdminAdminLayoutNewsIndexRoute
  '/_authenticated/admin/_adminLayout/onlineshop/': typeof AuthenticatedAdminAdminLayoutOnlineshopIndexRoute
  '/_authenticated/admin/_adminLayout/users/': typeof AuthenticatedAdminAdminLayoutUsersIndexRoute
  '/_authenticated/profile/_profileLayout/products/': typeof AuthenticatedProfileProfileLayoutProductsIndexRoute
  '/_authenticated/admin/_adminLayout/courses/courses/create': typeof AuthenticatedAdminAdminLayoutCoursesCoursesCreateRoute
  '/_authenticated/admin/_adminLayout/news/documents/create': typeof AuthenticatedAdminAdminLayoutNewsDocumentsCreateRoute
  '/_authenticated/admin/_adminLayout/news/news/create': typeof AuthenticatedAdminAdminLayoutNewsNewsCreateRoute
  '/_authenticated/admin/_adminLayout/onlineshop/products/create': typeof AuthenticatedAdminAdminLayoutOnlineshopProductsCreateRoute
  '/_authenticated/admin/_adminLayout/courses/courses/': typeof AuthenticatedAdminAdminLayoutCoursesCoursesIndexRoute
  '/_authenticated/admin/_adminLayout/news/documents/': typeof AuthenticatedAdminAdminLayoutNewsDocumentsIndexRoute
  '/_authenticated/admin/_adminLayout/news/news/': typeof AuthenticatedAdminAdminLayoutNewsNewsIndexRoute
  '/_authenticated/admin/_adminLayout/onlineshop/products/': typeof AuthenticatedAdminAdminLayoutOnlineshopProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/partners'
    | '/announcements/create'
    | '/announcements/service'
    | '/announcements/work'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/oneid'
    | '/auth/register'
    | '/auth/verify'
    | '/shop/categories'
    | '/announcements'
    | '/courses'
    | '/news'
    | '/shop'
    | '/admin'
    | '/profile'
    | '/announcements/service/$meta'
    | '/announcements/work/$meta'
    | '/courses/category/$meta'
    | '/courses/details/$meta'
    | '/news/categories/$meta'
    | '/news/news/$meta'
    | '/shop/details/$product'
    | '/admin/logs'
    | '/admin/overview'
    | '/profile/announcements'
    | '/profile/courses'
    | '/profile/edit'
    | '/profile/liked-courses'
    | '/profile/liked-products'
    | '/profile/messenger'
    | '/profile/notifications'
    | '/profile/overview'
    | '/profile/saved-announcements'
    | '/admin/'
    | '/profile/'
    | '/admin/announcements/$type'
    | '/admin/announcements/create'
    | '/admin/courses/categories'
    | '/admin/news/categories'
    | '/admin/onlineshop/categories'
    | '/admin/users/$role'
    | '/admin/users/create'
    | '/profile/products/create'
    | '/admin/announcements'
    | '/admin/courses'
    | '/admin/news'
    | '/admin/onlineshop'
    | '/admin/users'
    | '/profile/products'
    | '/admin/courses/courses/create'
    | '/admin/news/documents/create'
    | '/admin/news/news/create'
    | '/admin/onlineshop/products/create'
    | '/admin/courses/courses'
    | '/admin/news/documents'
    | '/admin/news/news'
    | '/admin/onlineshop/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/partners'
    | '/announcements/create'
    | '/announcements/service'
    | '/announcements/work'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/oneid'
    | '/auth/register'
    | '/auth/verify'
    | '/shop/categories'
    | '/announcements'
    | '/courses'
    | '/news'
    | '/shop'
    | '/admin'
    | '/profile'
    | '/announcements/service/$meta'
    | '/announcements/work/$meta'
    | '/courses/category/$meta'
    | '/courses/details/$meta'
    | '/news/categories/$meta'
    | '/news/news/$meta'
    | '/shop/details/$product'
    | '/admin/logs'
    | '/admin/overview'
    | '/profile/announcements'
    | '/profile/courses'
    | '/profile/edit'
    | '/profile/liked-courses'
    | '/profile/liked-products'
    | '/profile/messenger'
    | '/profile/notifications'
    | '/profile/overview'
    | '/profile/saved-announcements'
    | '/admin/announcements/$type'
    | '/admin/announcements/create'
    | '/admin/courses/categories'
    | '/admin/news/categories'
    | '/admin/onlineshop/categories'
    | '/admin/users/$role'
    | '/admin/users/create'
    | '/profile/products/create'
    | '/admin/announcements'
    | '/admin/courses'
    | '/admin/news'
    | '/admin/onlineshop'
    | '/admin/users'
    | '/profile/products'
    | '/admin/courses/courses/create'
    | '/admin/news/documents/create'
    | '/admin/news/news/create'
    | '/admin/onlineshop/products/create'
    | '/admin/courses/courses'
    | '/admin/news/documents'
    | '/admin/news/news'
    | '/admin/onlineshop/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/partners'
    | '/announcements/create'
    | '/announcements/service'
    | '/announcements/work'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/oneid'
    | '/auth/register'
    | '/auth/verify'
    | '/shop/categories'
    | '/announcements/'
    | '/courses/'
    | '/news/'
    | '/shop/'
    | '/_authenticated/admin'
    | '/_authenticated/admin/_adminLayout'
    | '/_authenticated/profile'
    | '/_authenticated/profile/_profileLayout'
    | '/announcements/service/$meta'
    | '/announcements/work/$meta'
    | '/courses/category/$meta'
    | '/courses/details/$meta'
    | '/news/categories/$meta'
    | '/news/news/$meta'
    | '/shop/details/$product'
    | '/_authenticated/admin/_adminLayout/logs'
    | '/_authenticated/admin/_adminLayout/overview'
    | '/_authenticated/profile/_profileLayout/announcements'
    | '/_authenticated/profile/_profileLayout/courses'
    | '/_authenticated/profile/_profileLayout/edit'
    | '/_authenticated/profile/_profileLayout/liked-courses'
    | '/_authenticated/profile/_profileLayout/liked-products'
    | '/_authenticated/profile/_profileLayout/messenger'
    | '/_authenticated/profile/_profileLayout/notifications'
    | '/_authenticated/profile/_profileLayout/overview'
    | '/_authenticated/profile/_profileLayout/saved-announcements'
    | '/_authenticated/admin/_adminLayout/'
    | '/_authenticated/profile/_profileLayout/'
    | '/_authenticated/admin/_adminLayout/announcements/$type'
    | '/_authenticated/admin/_adminLayout/announcements/create'
    | '/_authenticated/admin/_adminLayout/courses/categories'
    | '/_authenticated/admin/_adminLayout/news/categories'
    | '/_authenticated/admin/_adminLayout/onlineshop/categories'
    | '/_authenticated/admin/_adminLayout/users/$role'
    | '/_authenticated/admin/_adminLayout/users/create'
    | '/_authenticated/profile/_profileLayout/products/create'
    | '/_authenticated/admin/_adminLayout/announcements/'
    | '/_authenticated/admin/_adminLayout/courses/'
    | '/_authenticated/admin/_adminLayout/news/'
    | '/_authenticated/admin/_adminLayout/onlineshop/'
    | '/_authenticated/admin/_adminLayout/users/'
    | '/_authenticated/profile/_profileLayout/products/'
    | '/_authenticated/admin/_adminLayout/courses/courses/create'
    | '/_authenticated/admin/_adminLayout/news/documents/create'
    | '/_authenticated/admin/_adminLayout/news/news/create'
    | '/_authenticated/admin/_adminLayout/onlineshop/products/create'
    | '/_authenticated/admin/_adminLayout/courses/courses/'
    | '/_authenticated/admin/_adminLayout/news/documents/'
    | '/_authenticated/admin/_adminLayout/news/news/'
    | '/_authenticated/admin/_adminLayout/onlineshop/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PartnersRoute: typeof PartnersRoute
  AnnouncementsCreateRoute: typeof AnnouncementsCreateRoute
  AnnouncementsServiceRoute: typeof AnnouncementsServiceRouteWithChildren
  AnnouncementsWorkRoute: typeof AnnouncementsWorkRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthOneidRoute: typeof AuthOneidRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  ShopCategoriesRoute: typeof ShopCategoriesRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  CoursesCategoryMetaRoute: typeof CoursesCategoryMetaRoute
  CoursesDetailsMetaRoute: typeof CoursesDetailsMetaRoute
  NewsCategoriesMetaRoute: typeof NewsCategoriesMetaRoute
  NewsNewsMetaRoute: typeof NewsNewsMetaRoute
  ShopDetailsProductRoute: typeof ShopDetailsProductRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/categories': {
      id: '/shop/categories'
      path: '/shop/categories'
      fullPath: '/shop/categories'
      preLoaderRoute: typeof ShopCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/oneid': {
      id: '/auth/oneid'
      path: '/auth/oneid'
      fullPath: '/auth/oneid'
      preLoaderRoute: typeof AuthOneidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/work': {
      id: '/announcements/work'
      path: '/announcements/work'
      fullPath: '/announcements/work'
      preLoaderRoute: typeof AnnouncementsWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/service': {
      id: '/announcements/service'
      path: '/announcements/service'
      fullPath: '/announcements/service'
      preLoaderRoute: typeof AnnouncementsServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/create': {
      id: '/announcements/create'
      path: '/announcements/create'
      fullPath: '/announcements/create'
      preLoaderRoute: typeof AnnouncementsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/details/$product': {
      id: '/shop/details/$product'
      path: '/shop/details/$product'
      fullPath: '/shop/details/$product'
      preLoaderRoute: typeof ShopDetailsProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/news/$meta': {
      id: '/news/news/$meta'
      path: '/news/news/$meta'
      fullPath: '/news/news/$meta'
      preLoaderRoute: typeof NewsNewsMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/categories/$meta': {
      id: '/news/categories/$meta'
      path: '/news/categories/$meta'
      fullPath: '/news/categories/$meta'
      preLoaderRoute: typeof NewsCategoriesMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/details/$meta': {
      id: '/courses/details/$meta'
      path: '/courses/details/$meta'
      fullPath: '/courses/details/$meta'
      preLoaderRoute: typeof CoursesDetailsMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/category/$meta': {
      id: '/courses/category/$meta'
      path: '/courses/category/$meta'
      fullPath: '/courses/category/$meta'
      preLoaderRoute: typeof CoursesCategoryMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/work/$meta': {
      id: '/announcements/work/$meta'
      path: '/$meta'
      fullPath: '/announcements/work/$meta'
      preLoaderRoute: typeof AnnouncementsWorkMetaRouteImport
      parentRoute: typeof AnnouncementsWorkRoute
    }
    '/announcements/service/$meta': {
      id: '/announcements/service/$meta'
      path: '/$meta'
      fullPath: '/announcements/service/$meta'
      preLoaderRoute: typeof AnnouncementsServiceMetaRouteImport
      parentRoute: typeof AnnouncementsServiceRoute
    }
    '/_authenticated/profile/_profileLayout': {
      id: '/_authenticated/profile/_profileLayout'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileProfileLayoutRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/admin/_adminLayout': {
      id: '/_authenticated/admin/_adminLayout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/profile/_profileLayout/': {
      id: '/_authenticated/profile/_profileLayout/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileProfileLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedProfileProfileLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/': {
      id: '/_authenticated/admin/_adminLayout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/profile/_profileLayout/saved-announcements': {
      id: '/_authenticated/profile/_profileLayout/saved-announcements'
      path: '/saved-announcements'
      fullPath: '/profile/saved-announcements'
      preLoaderRoute: typeof AuthenticatedProfileProfileLayoutSavedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedProfileProfileLayoutRoute
    }
    '/_authenticated/profile/_profileLayout/overview': {
      id: '/_authenticated/profile/_profileLayout/overview'
      path: '/overview'
      fullPath: '/profile/overview'
      preLoaderRoute: typeof AuthenticatedProfileProfileLayoutOverviewRouteImport
      parentRoute: typeof AuthenticatedProfileProfileLayoutRoute
    }
    '/_authenticated/profile/_profileLayout/notifications': {
      id: '/_authenticated/profile/_profileLayout/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof AuthenticatedProfileProfileLayoutNotificationsRouteImport
      parentRoute: typeof AuthenticatedProfileProfileLayoutRoute
    }
    '/_authenticated/profile/_profileLayout/messenger': {
      id: '/_authenticated/profile/_profileLayout/messenger'
      path: '/messenger'
      fullPath: '/profile/messenger'
      preLoaderRoute: typeof AuthenticatedProfileProfileLayoutMessengerRouteImport
      parentRoute: typeof AuthenticatedProfileProfileLayoutRoute
    }
    '/_authenticated/profile/_profileLayout/liked-products': {
      id: '/_authenticated/profile/_profileLayout/liked-products'
      path: '/liked-products'
      fullPath: '/profile/liked-products'
      preLoaderRoute: typeof AuthenticatedProfileProfileLayoutLikedProductsRouteImport
      parentRoute: typeof AuthenticatedProfileProfileLayoutRoute
    }
    '/_authenticated/profile/_profileLayout/liked-courses': {
      id: '/_authenticated/profile/_profileLayout/liked-courses'
      path: '/liked-courses'
      fullPath: '/profile/liked-courses'
      preLoaderRoute: typeof AuthenticatedProfileProfileLayoutLikedCoursesRouteImport
      parentRoute: typeof AuthenticatedProfileProfileLayoutRoute
    }
    '/_authenticated/profile/_profileLayout/edit': {
      id: '/_authenticated/profile/_profileLayout/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileProfileLayoutEditRouteImport
      parentRoute: typeof AuthenticatedProfileProfileLayoutRoute
    }
    '/_authenticated/profile/_profileLayout/courses': {
      id: '/_authenticated/profile/_profileLayout/courses'
      path: '/courses'
      fullPath: '/profile/courses'
      preLoaderRoute: typeof AuthenticatedProfileProfileLayoutCoursesRouteImport
      parentRoute: typeof AuthenticatedProfileProfileLayoutRoute
    }
    '/_authenticated/profile/_profileLayout/announcements': {
      id: '/_authenticated/profile/_profileLayout/announcements'
      path: '/announcements'
      fullPath: '/profile/announcements'
      preLoaderRoute: typeof AuthenticatedProfileProfileLayoutAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedProfileProfileLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/overview': {
      id: '/_authenticated/admin/_adminLayout/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutOverviewRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/logs': {
      id: '/_authenticated/admin/_adminLayout/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutLogsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/profile/_profileLayout/products/': {
      id: '/_authenticated/profile/_profileLayout/products/'
      path: '/products'
      fullPath: '/profile/products'
      preLoaderRoute: typeof AuthenticatedProfileProfileLayoutProductsIndexRouteImport
      parentRoute: typeof AuthenticatedProfileProfileLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/users/': {
      id: '/_authenticated/admin/_adminLayout/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/onlineshop/': {
      id: '/_authenticated/admin/_adminLayout/onlineshop/'
      path: '/onlineshop'
      fullPath: '/admin/onlineshop'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutOnlineshopIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/news/': {
      id: '/_authenticated/admin/_adminLayout/news/'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutNewsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/courses/': {
      id: '/_authenticated/admin/_adminLayout/courses/'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/announcements/': {
      id: '/_authenticated/admin/_adminLayout/announcements/'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutAnnouncementsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/profile/_profileLayout/products/create': {
      id: '/_authenticated/profile/_profileLayout/products/create'
      path: '/products/create'
      fullPath: '/profile/products/create'
      preLoaderRoute: typeof AuthenticatedProfileProfileLayoutProductsCreateRouteImport
      parentRoute: typeof AuthenticatedProfileProfileLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/users/create': {
      id: '/_authenticated/admin/_adminLayout/users/create'
      path: '/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutUsersCreateRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/users/$role': {
      id: '/_authenticated/admin/_adminLayout/users/$role'
      path: '/users/$role'
      fullPath: '/admin/users/$role'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutUsersRoleRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/onlineshop/categories': {
      id: '/_authenticated/admin/_adminLayout/onlineshop/categories'
      path: '/onlineshop/categories'
      fullPath: '/admin/onlineshop/categories'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutOnlineshopCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/news/categories': {
      id: '/_authenticated/admin/_adminLayout/news/categories'
      path: '/news/categories'
      fullPath: '/admin/news/categories'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutNewsCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/courses/categories': {
      id: '/_authenticated/admin/_adminLayout/courses/categories'
      path: '/courses/categories'
      fullPath: '/admin/courses/categories'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutCoursesCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/announcements/create': {
      id: '/_authenticated/admin/_adminLayout/announcements/create'
      path: '/announcements/create'
      fullPath: '/admin/announcements/create'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutAnnouncementsCreateRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/announcements/$type': {
      id: '/_authenticated/admin/_adminLayout/announcements/$type'
      path: '/announcements/$type'
      fullPath: '/admin/announcements/$type'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutAnnouncementsTypeRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/onlineshop/products/': {
      id: '/_authenticated/admin/_adminLayout/onlineshop/products/'
      path: '/onlineshop/products'
      fullPath: '/admin/onlineshop/products'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutOnlineshopProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/news/news/': {
      id: '/_authenticated/admin/_adminLayout/news/news/'
      path: '/news/news'
      fullPath: '/admin/news/news'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutNewsNewsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/news/documents/': {
      id: '/_authenticated/admin/_adminLayout/news/documents/'
      path: '/news/documents'
      fullPath: '/admin/news/documents'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutNewsDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/courses/courses/': {
      id: '/_authenticated/admin/_adminLayout/courses/courses/'
      path: '/courses/courses'
      fullPath: '/admin/courses/courses'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutCoursesCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/onlineshop/products/create': {
      id: '/_authenticated/admin/_adminLayout/onlineshop/products/create'
      path: '/onlineshop/products/create'
      fullPath: '/admin/onlineshop/products/create'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutOnlineshopProductsCreateRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/news/news/create': {
      id: '/_authenticated/admin/_adminLayout/news/news/create'
      path: '/news/news/create'
      fullPath: '/admin/news/news/create'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutNewsNewsCreateRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/news/documents/create': {
      id: '/_authenticated/admin/_adminLayout/news/documents/create'
      path: '/news/documents/create'
      fullPath: '/admin/news/documents/create'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutNewsDocumentsCreateRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
    '/_authenticated/admin/_adminLayout/courses/courses/create': {
      id: '/_authenticated/admin/_adminLayout/courses/courses/create'
      path: '/courses/courses/create'
      fullPath: '/admin/courses/courses/create'
      preLoaderRoute: typeof AuthenticatedAdminAdminLayoutCoursesCoursesCreateRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLayoutRoute
    }
  }
}

interface AuthenticatedAdminAdminLayoutRouteChildren {
  AuthenticatedAdminAdminLayoutLogsRoute: typeof AuthenticatedAdminAdminLayoutLogsRoute
  AuthenticatedAdminAdminLayoutOverviewRoute: typeof AuthenticatedAdminAdminLayoutOverviewRoute
  AuthenticatedAdminAdminLayoutIndexRoute: typeof AuthenticatedAdminAdminLayoutIndexRoute
  AuthenticatedAdminAdminLayoutAnnouncementsTypeRoute: typeof AuthenticatedAdminAdminLayoutAnnouncementsTypeRoute
  AuthenticatedAdminAdminLayoutAnnouncementsCreateRoute: typeof AuthenticatedAdminAdminLayoutAnnouncementsCreateRoute
  AuthenticatedAdminAdminLayoutCoursesCategoriesRoute: typeof AuthenticatedAdminAdminLayoutCoursesCategoriesRoute
  AuthenticatedAdminAdminLayoutNewsCategoriesRoute: typeof AuthenticatedAdminAdminLayoutNewsCategoriesRoute
  AuthenticatedAdminAdminLayoutOnlineshopCategoriesRoute: typeof AuthenticatedAdminAdminLayoutOnlineshopCategoriesRoute
  AuthenticatedAdminAdminLayoutUsersRoleRoute: typeof AuthenticatedAdminAdminLayoutUsersRoleRoute
  AuthenticatedAdminAdminLayoutUsersCreateRoute: typeof AuthenticatedAdminAdminLayoutUsersCreateRoute
  AuthenticatedAdminAdminLayoutAnnouncementsIndexRoute: typeof AuthenticatedAdminAdminLayoutAnnouncementsIndexRoute
  AuthenticatedAdminAdminLayoutCoursesIndexRoute: typeof AuthenticatedAdminAdminLayoutCoursesIndexRoute
  AuthenticatedAdminAdminLayoutNewsIndexRoute: typeof AuthenticatedAdminAdminLayoutNewsIndexRoute
  AuthenticatedAdminAdminLayoutOnlineshopIndexRoute: typeof AuthenticatedAdminAdminLayoutOnlineshopIndexRoute
  AuthenticatedAdminAdminLayoutUsersIndexRoute: typeof AuthenticatedAdminAdminLayoutUsersIndexRoute
  AuthenticatedAdminAdminLayoutCoursesCoursesCreateRoute: typeof AuthenticatedAdminAdminLayoutCoursesCoursesCreateRoute
  AuthenticatedAdminAdminLayoutNewsDocumentsCreateRoute: typeof AuthenticatedAdminAdminLayoutNewsDocumentsCreateRoute
  AuthenticatedAdminAdminLayoutNewsNewsCreateRoute: typeof AuthenticatedAdminAdminLayoutNewsNewsCreateRoute
  AuthenticatedAdminAdminLayoutOnlineshopProductsCreateRoute: typeof AuthenticatedAdminAdminLayoutOnlineshopProductsCreateRoute
  AuthenticatedAdminAdminLayoutCoursesCoursesIndexRoute: typeof AuthenticatedAdminAdminLayoutCoursesCoursesIndexRoute
  AuthenticatedAdminAdminLayoutNewsDocumentsIndexRoute: typeof AuthenticatedAdminAdminLayoutNewsDocumentsIndexRoute
  AuthenticatedAdminAdminLayoutNewsNewsIndexRoute: typeof AuthenticatedAdminAdminLayoutNewsNewsIndexRoute
  AuthenticatedAdminAdminLayoutOnlineshopProductsIndexRoute: typeof AuthenticatedAdminAdminLayoutOnlineshopProductsIndexRoute
}

const AuthenticatedAdminAdminLayoutRouteChildren: AuthenticatedAdminAdminLayoutRouteChildren =
  {
    AuthenticatedAdminAdminLayoutLogsRoute:
      AuthenticatedAdminAdminLayoutLogsRoute,
    AuthenticatedAdminAdminLayoutOverviewRoute:
      AuthenticatedAdminAdminLayoutOverviewRoute,
    AuthenticatedAdminAdminLayoutIndexRoute:
      AuthenticatedAdminAdminLayoutIndexRoute,
    AuthenticatedAdminAdminLayoutAnnouncementsTypeRoute:
      AuthenticatedAdminAdminLayoutAnnouncementsTypeRoute,
    AuthenticatedAdminAdminLayoutAnnouncementsCreateRoute:
      AuthenticatedAdminAdminLayoutAnnouncementsCreateRoute,
    AuthenticatedAdminAdminLayoutCoursesCategoriesRoute:
      AuthenticatedAdminAdminLayoutCoursesCategoriesRoute,
    AuthenticatedAdminAdminLayoutNewsCategoriesRoute:
      AuthenticatedAdminAdminLayoutNewsCategoriesRoute,
    AuthenticatedAdminAdminLayoutOnlineshopCategoriesRoute:
      AuthenticatedAdminAdminLayoutOnlineshopCategoriesRoute,
    AuthenticatedAdminAdminLayoutUsersRoleRoute:
      AuthenticatedAdminAdminLayoutUsersRoleRoute,
    AuthenticatedAdminAdminLayoutUsersCreateRoute:
      AuthenticatedAdminAdminLayoutUsersCreateRoute,
    AuthenticatedAdminAdminLayoutAnnouncementsIndexRoute:
      AuthenticatedAdminAdminLayoutAnnouncementsIndexRoute,
    AuthenticatedAdminAdminLayoutCoursesIndexRoute:
      AuthenticatedAdminAdminLayoutCoursesIndexRoute,
    AuthenticatedAdminAdminLayoutNewsIndexRoute:
      AuthenticatedAdminAdminLayoutNewsIndexRoute,
    AuthenticatedAdminAdminLayoutOnlineshopIndexRoute:
      AuthenticatedAdminAdminLayoutOnlineshopIndexRoute,
    AuthenticatedAdminAdminLayoutUsersIndexRoute:
      AuthenticatedAdminAdminLayoutUsersIndexRoute,
    AuthenticatedAdminAdminLayoutCoursesCoursesCreateRoute:
      AuthenticatedAdminAdminLayoutCoursesCoursesCreateRoute,
    AuthenticatedAdminAdminLayoutNewsDocumentsCreateRoute:
      AuthenticatedAdminAdminLayoutNewsDocumentsCreateRoute,
    AuthenticatedAdminAdminLayoutNewsNewsCreateRoute:
      AuthenticatedAdminAdminLayoutNewsNewsCreateRoute,
    AuthenticatedAdminAdminLayoutOnlineshopProductsCreateRoute:
      AuthenticatedAdminAdminLayoutOnlineshopProductsCreateRoute,
    AuthenticatedAdminAdminLayoutCoursesCoursesIndexRoute:
      AuthenticatedAdminAdminLayoutCoursesCoursesIndexRoute,
    AuthenticatedAdminAdminLayoutNewsDocumentsIndexRoute:
      AuthenticatedAdminAdminLayoutNewsDocumentsIndexRoute,
    AuthenticatedAdminAdminLayoutNewsNewsIndexRoute:
      AuthenticatedAdminAdminLayoutNewsNewsIndexRoute,
    AuthenticatedAdminAdminLayoutOnlineshopProductsIndexRoute:
      AuthenticatedAdminAdminLayoutOnlineshopProductsIndexRoute,
  }

const AuthenticatedAdminAdminLayoutRouteWithChildren =
  AuthenticatedAdminAdminLayoutRoute._addFileChildren(
    AuthenticatedAdminAdminLayoutRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminLayoutRoute: typeof AuthenticatedAdminAdminLayoutRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminLayoutRoute:
    AuthenticatedAdminAdminLayoutRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedProfileProfileLayoutRouteChildren {
  AuthenticatedProfileProfileLayoutAnnouncementsRoute: typeof AuthenticatedProfileProfileLayoutAnnouncementsRoute
  AuthenticatedProfileProfileLayoutCoursesRoute: typeof AuthenticatedProfileProfileLayoutCoursesRoute
  AuthenticatedProfileProfileLayoutEditRoute: typeof AuthenticatedProfileProfileLayoutEditRoute
  AuthenticatedProfileProfileLayoutLikedCoursesRoute: typeof AuthenticatedProfileProfileLayoutLikedCoursesRoute
  AuthenticatedProfileProfileLayoutLikedProductsRoute: typeof AuthenticatedProfileProfileLayoutLikedProductsRoute
  AuthenticatedProfileProfileLayoutMessengerRoute: typeof AuthenticatedProfileProfileLayoutMessengerRoute
  AuthenticatedProfileProfileLayoutNotificationsRoute: typeof AuthenticatedProfileProfileLayoutNotificationsRoute
  AuthenticatedProfileProfileLayoutOverviewRoute: typeof AuthenticatedProfileProfileLayoutOverviewRoute
  AuthenticatedProfileProfileLayoutSavedAnnouncementsRoute: typeof AuthenticatedProfileProfileLayoutSavedAnnouncementsRoute
  AuthenticatedProfileProfileLayoutIndexRoute: typeof AuthenticatedProfileProfileLayoutIndexRoute
  AuthenticatedProfileProfileLayoutProductsCreateRoute: typeof AuthenticatedProfileProfileLayoutProductsCreateRoute
  AuthenticatedProfileProfileLayoutProductsIndexRoute: typeof AuthenticatedProfileProfileLayoutProductsIndexRoute
}

const AuthenticatedProfileProfileLayoutRouteChildren: AuthenticatedProfileProfileLayoutRouteChildren =
  {
    AuthenticatedProfileProfileLayoutAnnouncementsRoute:
      AuthenticatedProfileProfileLayoutAnnouncementsRoute,
    AuthenticatedProfileProfileLayoutCoursesRoute:
      AuthenticatedProfileProfileLayoutCoursesRoute,
    AuthenticatedProfileProfileLayoutEditRoute:
      AuthenticatedProfileProfileLayoutEditRoute,
    AuthenticatedProfileProfileLayoutLikedCoursesRoute:
      AuthenticatedProfileProfileLayoutLikedCoursesRoute,
    AuthenticatedProfileProfileLayoutLikedProductsRoute:
      AuthenticatedProfileProfileLayoutLikedProductsRoute,
    AuthenticatedProfileProfileLayoutMessengerRoute:
      AuthenticatedProfileProfileLayoutMessengerRoute,
    AuthenticatedProfileProfileLayoutNotificationsRoute:
      AuthenticatedProfileProfileLayoutNotificationsRoute,
    AuthenticatedProfileProfileLayoutOverviewRoute:
      AuthenticatedProfileProfileLayoutOverviewRoute,
    AuthenticatedProfileProfileLayoutSavedAnnouncementsRoute:
      AuthenticatedProfileProfileLayoutSavedAnnouncementsRoute,
    AuthenticatedProfileProfileLayoutIndexRoute:
      AuthenticatedProfileProfileLayoutIndexRoute,
    AuthenticatedProfileProfileLayoutProductsCreateRoute:
      AuthenticatedProfileProfileLayoutProductsCreateRoute,
    AuthenticatedProfileProfileLayoutProductsIndexRoute:
      AuthenticatedProfileProfileLayoutProductsIndexRoute,
  }

const AuthenticatedProfileProfileLayoutRouteWithChildren =
  AuthenticatedProfileProfileLayoutRoute._addFileChildren(
    AuthenticatedProfileProfileLayoutRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileProfileLayoutRoute: typeof AuthenticatedProfileProfileLayoutRouteWithChildren
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileProfileLayoutRoute:
    AuthenticatedProfileProfileLayoutRouteWithChildren,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AnnouncementsServiceRouteChildren {
  AnnouncementsServiceMetaRoute: typeof AnnouncementsServiceMetaRoute
}

const AnnouncementsServiceRouteChildren: AnnouncementsServiceRouteChildren = {
  AnnouncementsServiceMetaRoute: AnnouncementsServiceMetaRoute,
}

const AnnouncementsServiceRouteWithChildren =
  AnnouncementsServiceRoute._addFileChildren(AnnouncementsServiceRouteChildren)

interface AnnouncementsWorkRouteChildren {
  AnnouncementsWorkMetaRoute: typeof AnnouncementsWorkMetaRoute
}

const AnnouncementsWorkRouteChildren: AnnouncementsWorkRouteChildren = {
  AnnouncementsWorkMetaRoute: AnnouncementsWorkMetaRoute,
}

const AnnouncementsWorkRouteWithChildren =
  AnnouncementsWorkRoute._addFileChildren(AnnouncementsWorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PartnersRoute: PartnersRoute,
  AnnouncementsCreateRoute: AnnouncementsCreateRoute,
  AnnouncementsServiceRoute: AnnouncementsServiceRouteWithChildren,
  AnnouncementsWorkRoute: AnnouncementsWorkRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthOneidRoute: AuthOneidRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  ShopCategoriesRoute: ShopCategoriesRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  CoursesCategoryMetaRoute: CoursesCategoryMetaRoute,
  CoursesDetailsMetaRoute: CoursesDetailsMetaRoute,
  NewsCategoriesMetaRoute: NewsCategoriesMetaRoute,
  NewsNewsMetaRoute: NewsNewsMetaRoute,
  ShopDetailsProductRoute: ShopDetailsProductRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
